name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do codigo
      uses: actions/checkout@v3
      
    - name: Configurar o JDK 17 (Java Correto)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Dar permissao de execucao ao Gradle
      run: chmod +x gradlew

    - name: Compilar o Aplicativo (Gerar APK)
      run: ./gradlew assembleDebug

    - name: Enviar o APK Pronto para Download
      uses: actions/upload-artifact@v3
      with:
        name: ESP32-OTG-App
        path: app/build/outputs/apk/debug/app-debug.apk
        
